ibm:
  mq:
    queueManager: QM1
    channel: DEV.ADMIN.SVRCONN
    connName: localhost(1414)
    user: admin
    password: passw0rd
spring:
  jms:
    pub-sub-domain: true
    cache:
      enabled: false
  datasource:
    url: jdbc:hsqldb:file:./poc-mqserie-db
  jpa:
    hibernate:
      ddl-auto: update
